// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9CvXVWc7kQeLINs2wEyv8RxqIG4bXBw',
    appId: '1:252630645661:web:c567ddb7b72d67d7dd8d74',
    messagingSenderId: '252630645661',
    projectId: 'fahmi-42d87',
    authDomain: 'fahmi-42d87.firebaseapp.com',
    storageBucket: 'fahmi-42d87.appspot.com',
    measurementId: 'G-SDJS9SC957',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCKeQsm9mKDRBQHObqh62ZERXR1VjCV8',
    appId: '1:252630645661:android:535ee00c1dd3fc0edd8d74',
    messagingSenderId: '252630645661',
    projectId: 'fahmi-42d87',
    storageBucket: 'fahmi-42d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsO_e7AL9FTwsp7iFq3NW6JySQOdm9XWU',
    appId: '1:252630645661:ios:33fe8cbcf1bce4f2dd8d74',
    messagingSenderId: '252630645661',
    projectId: 'fahmi-42d87',
    storageBucket: 'fahmi-42d87.appspot.com',
    iosBundleId: 'com.example.intt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsO_e7AL9FTwsp7iFq3NW6JySQOdm9XWU',
    appId: '1:252630645661:ios:33fe8cbcf1bce4f2dd8d74',
    messagingSenderId: '252630645661',
    projectId: 'fahmi-42d87',
    storageBucket: 'fahmi-42d87.appspot.com',
    iosBundleId: 'com.example.intt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn9CvXVWc7kQeLINs2wEyv8RxqIG4bXBw',
    appId: '1:252630645661:web:ce0110e02d7a5f49dd8d74',
    messagingSenderId: '252630645661',
    projectId: 'fahmi-42d87',
    authDomain: 'fahmi-42d87.firebaseapp.com',
    storageBucket: 'fahmi-42d87.appspot.com',
    measurementId: 'G-H5DZC30V6E',
  );
}
